apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tusker-home
  namespace: hermes
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
